### PR TITLE
Update README.md tailwind config to have stwui content

### PR DESCRIPTION
**Pull request by KevM**
My node modules directory for a boilerplate skeleton app was up one folder. I noticed that the tailwind config file content was not updated in the code-fenced example, so I added it.

### CODE REVIEW

**Comment by KevM** [comment]
Looks like the installation page on the docs also need this change. I can add if you like bit I just made this PR from GitHub so adding a file to this PR is a bit tricky unless I clone.

**Comment by N00nDay** [comment]
What process are you using for starting a sveltekit project? using `npm create svelte@latest` should allow you to create a skeleton project and after running `npm install` will place the `node_modules` folder at the root of the project not up one directory. Can you post a screenshot so I can see whats happening?

**Comment by N00nDay** [comment]
Closed this branch as the `node_modules` directory for a sveltekit project is at the root.

**Comment by KevM** [comment]
FYI 

The readme and instructions markdown documents area still missing the example of adding the stwui to the tailwind config content node.

``` js
content: 
  [
    './src/**/*.{html,js,svelte,ts}',
    './node_modules/stwui/**/*.{svelte,js,ts,html}'
  ],
```

**Pull request merged**
