### PR TITLE
allow `Button` accept `href` attribute

### LINKED ISSUE #79: [feature-request] Allow `Button` to accept `href` attribute
As topic.

### PR DESCRIPTION
**Pull request by cayter**
Closes #79

### CODE REVIEW

**Comment by N00nDay** [comment]
I see you added `clsx` to the project in place of `twmerge`. What is your reasoning for this? I like the update in general and I completely agree that a "link" button should take an href. I just want to avoid cluttering multiple class joiner packages if possible. Full transparency, I have never used "clsx" before.

**Comment by cayter** [comment]
> I see you added `clsx` to the project in place of `twmerge`. What is your reasoning for this? I like the update in general and I completely agree that a "link" button should take an href. I just want to avoid cluttering multiple class joiner packages if possible. Full transparency, I have never used "clsx" before.

Libraries like `clsx` allows us to simplify the `class` string composing especially when we have to deal with conditional classes, e.g.

Before
```ts
let defaultClass = 'btn group relative inline-flex justify-center items-center font-medium active:hover:animate-none active:hover:scale-95 outline-none';
		
if (loading) {
  defaultClass += ' cursor-wait';
} else {
  defaultClass += ' cursor-pointer';
}
	
$: finalClass = twMerge(defaultClass, $$props.class);
```

After
```ts
$: finalClass = clsx({
  'btn group relative inline-flex justify-center items-center font-medium active:hover:animate-none active:hover:scale-95 outline-none',
  {
    'cursor-wait': loading,
    'cursor-pointer': !loading
  }
})
```

With `clsx`, we'd just have to extend the classes with more conditions in the object instead of many lines of `if..else if..else`.

**Comment by N00nDay** [comment]
Nice! I like the conditional properties as it cleans up the if/else statements and kind of has a similar feel to Svelte's conditional class statements "class:something". The original reason for going to "twmerge" was to allow end users to overwrite current classes assigned to the component. For instance, if you have:
```
<Alert type="warn" class="bg-red-500">
   <Alert.Title slot="title">Title</Alert.Title>
</Alert>
```
Instead of the `Alert` being yellow using `type="warn"` it would be red as the user can override the underlying class as desired. Is this how `clsx` works as well? I am assuming it doesn't as it doesn't know the difference between the different TailwindCSS classes but maybe I am missing something.

**Comment by N00nDay** [comment]
> > Nice! I like the conditional properties as it cleans up the if/else statements and kind of has a similar feel to Svelte's conditional class statements "class:something". The original reason for going to "twmerge" was to allow end users to overwrite current classes assigned to the component. For instance, if you have:
> > ```
> > <Alert type="warn" class="bg-red-500">
> >    <Alert.Title slot="title">Title</Alert.Title>
> > </Alert>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Instead of the `Alert` being yellow using `type="warn"` it would be red as the user can override the underlying class as desired. Is this how `clsx` works as well? I am assuming it doesn't as it doesn't know the difference between the different TailwindCSS classes but maybe I am missing something.
> 
> For this case, I would do something like this:
> 
> Alert.svelte
> 
> ```svelte
> <script lang="ts">
> export let type: 'error' | 'warn' = 'error';
> 
> const typeToColor: Record<keyof type, string> = {
>   error: 'red',
>   warn: 'yellow',
> };
> 
> const classes = clsx(
>   `bg-${typeToColor[color]}-500`, 
>   {
>     ...
>   });
> </script>
> ```
> 
> App.svelte
> 
> ```svelte
> <Alert type="warn">
>   ...
> </Alert>
> ```

I may have provided a bad example. I know that is how we would handle it for the types but if the developer using STWUI wants to override the styling using tailwind classes they should be able to do so. Components should be customizable by the developer as they see fit, this is one area that still needs a little work on STWUI and is on the roadmap.

I am not sure if `clsx` can do this as it is not aware of TailwindCSS classes. If the `Alert` component has `bg-yellow-300` but I as the developer want it to be `bg-red-600` I just have to pass `class="bg-red-600"` and it works as expected by the developer. `twmerge` knows that `bg-yellow-300` and `bg-red-600` are both `background-colors` and it will take the last one `bg-red-600` and use it instead of `bg-yellow-300`. Most other packages I have found treat this as a roll of the dice by including both classes and leaving it up to the browser to decide. `twmerge` physically removes the class that should not be used so the developer always knows what they are going to get. 

Does that clear up my concern with utilizing `clsx`?

**Comment by cayter** [comment]
Oh you mean the TW classes passed from outside of the component. Yes, IIRC it still works.

Alert.svelte
```svelte
<script lang="ts">
export let type: 'error' | 'warn' = 'error';

const typeToColor: Record<keyof type, string> = {
  error: 'red',
  warn: 'yellow',
};

const classes = clsx(
  `bg-${typeToColor[color]}-500`, 
  {
    ...
  },
  $$props.class // this class from outside of the component would override the classes we defined above
);
</script>
```

**Comment by N00nDay** [comment]
> ```svelte
> utside of the component would override the classes we defined above
> ```

Awesome! I like the changes you proposed and I may even consider swapping out `twmerge` with `clsx` for the entire project. I should have some time tonight or tomorrow to look over the pull request in full and as long as everything checks out merge it. I appreciate the contribution!

**Comment by N00nDay** [comment]
I was in the middle of another commit and decided to just add this to what I was working on. I appreciate the work and turning the project onto clsx as I think it is going to clean up some of the code once I get a chance to swap out twmerge with it. It has also allowed some components that were originally not able to be overridden by user to be overridden now. Thanks for the work and I hope you will consider contributing in the future.

**Pull request closed without merging**
